version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.6.0
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    # Remove networks section, if you don't use this service over HTTPS
    networks:
      - https
    environment:
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${UI_PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
    ports:
      - "${UI_PORT}:9000"
      - "${SSH_PORT}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

# Remove networks section, if you don't use this service over HTTPS
networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
