version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.11.1
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - https
    ports:
      - "${UI_PORT}:9000"
      - "${SSH_PORT}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
